
package frontend;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "AdminService", targetNamespace = "http://frontend/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface AdminService {


    /**
     * 
     * @param date
     * @param roomNumber
     * @param timeSlot
     * @param userID
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://frontend/AdminService/createRoomRequest", output = "http://frontend/AdminService/createRoomResponse")
    public String createRoom(
        @WebParam(name = "roomNumber", partName = "roomNumber")
        String roomNumber,
        @WebParam(name = "date", partName = "date")
        String date,
        @WebParam(name = "timeSlot", partName = "timeSlot")
        String timeSlot,
        @WebParam(name = "userID", partName = "userID")
        String userID);

    /**
     * 
     * @param date
     * @param roomNumber
     * @param timeSlot
     * @param userID
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://frontend/AdminService/deleteRoomRequest", output = "http://frontend/AdminService/deleteRoomResponse")
    public String deleteRoom(
        @WebParam(name = "roomNumber", partName = "roomNumber")
        String roomNumber,
        @WebParam(name = "date", partName = "date")
        String date,
        @WebParam(name = "timeSlot", partName = "timeSlot")
        String timeSlot,
        @WebParam(name = "userID", partName = "userID")
        String userID);

}
