
package frontend;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AdminServiceImplService", targetNamespace = "http://frontend/", wsdlLocation = "http://localhost:8800/AdminService?wsdl")
public class AdminServiceImplService
    extends Service
{

    private final static URL ADMINSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException ADMINSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName ADMINSERVICEIMPLSERVICE_QNAME = new QName("http://frontend/", "AdminServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8800/AdminService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ADMINSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        ADMINSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public AdminServiceImplService() {
        super(__getWsdlLocation(), ADMINSERVICEIMPLSERVICE_QNAME);
    }

    public AdminServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ADMINSERVICEIMPLSERVICE_QNAME, features);
    }

    public AdminServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, ADMINSERVICEIMPLSERVICE_QNAME);
    }

    public AdminServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ADMINSERVICEIMPLSERVICE_QNAME, features);
    }

    public AdminServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AdminServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AdminService
     */
    @WebEndpoint(name = "AdminServicePort")
    public AdminService getAdminServicePort() {
        return super.getPort(new QName("http://frontend/", "AdminServicePort"), AdminService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AdminService
     */
    @WebEndpoint(name = "AdminServicePort")
    public AdminService getAdminServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://frontend/", "AdminServicePort"), AdminService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ADMINSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw ADMINSERVICEIMPLSERVICE_EXCEPTION;
        }
        return ADMINSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
